#SERVER
APP_ENV: "local"
SERVER_PORT: "6060"

REDIS_HOST: "127.0.0.1:6379"
REDIS_DB: 0

NSQD_HOST: "127.0.0.1:4150"
NSQD_MAXINFLIGHT: 200
NSQD_DIALTIMEOUT: 10 # SECOND
NSQD_MAXATTEMPTS: 30
NSQD_MAXREQUEUEDELAY: 500 # MILLISECOND

WORKER_POOL_SIZE: 200
WORKER_MAX_OPEN: 160
WORKER_IDLE: 60
WORKER_LIFE_TIME: 600

GRACE_SHUTDOWN_TIME: 3